# Site settings
title:         천각블로그
description:    "천각블로그에서 발표한 게시글을 소개합니다."
internal_title: 천각
url:            "https://genius0928.github.io/"
destination:    docs

google_analytics: True

# Author
author:
  name:         천각

# Build settings
markdown:       kramdown
include:
  - _pages
future:         true

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:slug
paginate:       10

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
  - vendor
  - CODEOWNERS
  - CONTRIBUTING.md
  - LICENSE
  - NOTICE.md
  - README.md
  - build.sh
  - serve.sh
